# Generated by Django 5.2.6 on 2025-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nom_english', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/categorie/')),
                ('nb_sous_categorie', models.IntegerField(default=0, editable=False)),
                ('nb_produits', models.IntegerField(default=0, editable=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('description_english', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
