# Generated by Django 5.2.6 on 2025-09-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nom_english', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/sous categorie/')),
                ('nb_produits', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('description_english', models.CharField(blank=True, max_length=255, null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categorie')),
            ],
        ),
    ]
