# Generated by Django 5.2.6 on 2025-09-30 14:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_souscategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=50)),
                ('preference_contact', models.CharField(choices=[('whatsapp_appel', ' Via Appel Whatsapp'), ('telephone_appel', 'Via Appel Telephonqiue'), ('email', 'Via email')], max_length=50)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('adresse_postale', models.CharField(default='Maroc', max_length=100)),
                ('type_fournisseur', models.CharField(choices=[('professionnel', ' Professionnel'), ('particulier', ' Particulier')], max_length=15)),
                ('nb_produits', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, unique=True)),
                ('titre_english', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/promotion/')),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dollar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pound', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dollar_canadien', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Taux de Change',
                'verbose_name_plural': 'Taux de Change',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('reference', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('nom_produit', models.CharField(max_length=100, unique=True)),
                ('nom_produit_english', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=100)),
                ('dimension', models.CharField(blank=True, max_length=100, null=True)),
                ('materiaux', models.CharField(max_length=100)),
                ('materiaux_english', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100, null=True)),
                ('description_english', models.TextField(max_length=100, null=True)),
                ('couleur', models.CharField(max_length=100)),
                ('couleur_english', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/produit/')),
                ('en_stock', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('archive', models.BooleanField(default=False)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='PrixEnDevisePromotionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_dhs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('prix_euro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('prix_dollar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('prix_pound', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('prix_dollar_canadien', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.produit')),
            ],
        ),
        migrations.CreateModel(
            name='PrixEnDevise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_dhs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('prix_euro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('prix_dollar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('prix_pound', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('prix_dollar_canadien', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/produits/images-supplementaires/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitAvecSousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produit')),
                ('sous_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.souscategorie')),
            ],
            options={
                'verbose_name': 'Produit avec Sous-catégorie',
                'verbose_name_plural': 'Produits avec Sous-catégorie',
            },
        ),
        migrations.CreateModel(
            name='ProduitComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementaires', to='store.produit')),
                ('produit_complementaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complementaire_de', to='store.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitSimilaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similaires', to='store.produit')),
                ('produit_similaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similaires_de', to='store.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitAvecPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_prt', to='store.produit')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.promotion')),
            ],
            options={
                'verbose_name': 'Produit en Promotion',
                'verbose_name_plural': 'Produits en Promotion',
            },
        ),
    ]
