# Generated by Django 5.2.6 on 2025-10-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_fournisseur_promotion_tauxchange_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_english',
            field=models.CharField(default='', max_length=200),
        ),
    ]
