# Generated by Django 5.2.6 on 2025-10-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_promotion_description_promotion_description_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_commande', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSousCategoriePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.produitavecsouscategorie')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_sous_categorie', to='store.panier')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPromotionPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.produitavecpromotion')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_promotion', to='store.panier')),
            ],
        ),
    ]
