# Generated by Django 5.2.6 on 2025-09-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('question', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('reponse', models.TextField()),
                ('question_english', models.CharField(max_length=100, unique=True)),
                ('reponse_english', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('preference_contact', models.CharField(choices=[('whatsapp_appel', ' Via Appel Whatsapp'), ('telephone_appel', 'Via Appel Telephonqiue'), ('email', 'Via email')], max_length=50)),
                ('etat', models.CharField(choices=[('tr', 'Traité'), ('nt', 'Non Traité')], default='nt', max_length=50)),
                ('sujet', models.CharField(choices=[('sc', 'Suivi Commande'), ('ap', 'A propos d un produit'), ('as', 'A propos Adiba Interieur'), ('au', 'Autre')], max_length=50)),
                ('message', models.TextField()),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('texte', models.CharField(max_length=100)),
                ('texte_english', models.CharField(max_length=100)),
                ('nom_complet', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField()),
            ],
        ),
    ]
